### ISSUE TITLE
Typo in "errorStatus.errorValue" extraction. ("&&" should be "&" in multiple places.

### ISSUE THREAD

**Issue by Fishybob** [onethinx/DemoKit#2]
in SendOnSwitch main.c 

  "&&" should be "&" in multiple places. Incorrect shifts, incorrect formats, etc...

Fixed lines:
sprintf( buffer, "\r\nParameter error: 0x%lx", (errorStatus.errorValue >> 0) & 0xFF );
sprintf( buffer, "\r\nRadio Error:     0x%lx", (errorStatus.errorValue >> 8) & 0xFF );
sprintf( buffer, "\r\nMAC Error:       0x%lx", (errorStatus.errorValue >> 16) & 0xFF );
sprintf( buffer, "\r\nSystem Error:    0x%lx", (errorStatus.errorValue >> 24) & 0xFF );

Scott.

**Comment by RolfNoot** [comment]
Thanks! Updated!
